### ISSUE TITLE
일이 끝나지 않는 짤 추가

### ISSUE THREAD

**Issue by premist** [zvuc/1#1]
> **@kiding:** 
> 즙구 선생님 일이 끝나지 않는 짤 만들어 주세요

Reference: https://twitter.com/kid1ng/status/503566715846803456

**Comment by premist** [comment]
는 [이미 있네요](http://usagi.moe/1/).. ㅈㅅ

**Comment by kiding** [comment]
깃헙 레포도 있었습니까 이거

**Comment by zvuc** [comment]
방금 만들었슴니다 ㅎㅎ..
